- hosts: front-end
  become: yes

  tasks:
    - name: Ensure yum repository is registered
      yum_repository:
        name: nginx-repo
        description: Official nginx repository
        baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck: no

    - name: Ensure packages are installed
      package:
        name:
          - ca-certificates
          - nginx-1.14.0

    - name: Ensure nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy the index file
      copy:
        src: project/index.html
        dest: /usr/share/nginx/html
        owner: nginx

    - name: Copy applications files
      copy:
        src: project/target/scala-2.12/front-end-opt.js
        dest: /usr/share/nginx/html/js/
        owner: nginx

    - name: Ensure hardened security is added
      blockinfile:
        path: /etc/nginx/conf.d/security.conf
        block: |
          server_tokens off;
          client_header_buffer_size   4k;
          large_client_header_buffers 8 8k;
          client_max_body_size 20m;
          connection_pool_size 8192;
          request_pool_size 8k;
        create: yes
      notify: RELOAD_NGINX

    - name: Ensure caching map is enabled
      blockinfile:
        path: /etc/nginx/conf.d/caching.conf
        block: |
          map $sent_http_content_type $expires {
              default                    off;
              text/html                  epoch;
              text/css                   max;
              application/javascript     max;
              ~image/                    max;
          }
        create: yes
      notify: RELOAD_NGINX

    - name: Ensure 'expires' is applied to the server
      lineinfile:
        line: expires $expires;
        path: /etc/nginx/conf.d/default.conf
        insertbefore: "#error_page  404"
      notify: RELOAD_NGINX

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      listen: RELOAD_NGINX

# Slack webhook url
# https://hooks.slack.com/services/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
