---
- name: Ensure the maximum number of file descriptors is increased
  pam_limits:
    domain: "{{item.domain}}"
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  loop:
    - { domain: 'root', limit_type: 'soft', limit_item: 'nofile', value: '{{ulimit}}' }
    - { domain: 'root', limit_type: 'hard', limit_item: 'nofile', value: '{{ulimit}}' }
    - { domain: '*', limit_type: 'hard', limit_item: 'nofile', value: '{{ulimit}}' }
    - { domain: '*', limit_type: 'soft', limit_item: 'nofile', value: '{{ulimit}}' }
- name: Ensure  Network Kernel Parameters are optimised
  sysctl:
    name: "{{item.path}}"
    value: "{{item.value}}"
    state: present
  loop:
    - { path: 'net.core.somaxconn', value: '1024'}
    - { path: 'net.core.netdev_max_backlog', value: '5000'}
    - { path: 'net.core.rmem_max', value: '16777216'}
    - { path: 'net.core.wmem_max', value: '16777216'}
    - { path: 'net.ipv4.tcp_wmem', value: '4096 12582912 16777216'}
    - { path: 'net.ipv4.tcp_rmem', value: '4096 12582912 16777216'}
    - { path: 'net.ipv4.tcp_max_syn_backlog', value: '8096'}
    - { path: 'net.ipv4.tcp_slow_start_after_idle', value: '0'}
    - { path: 'net.ipv4.tcp_tw_reuse', value: '1'}
    - { path: 'net.ipv4.ip_local_port_range', value: '10240 65535'}
